Metrics/MethodLength:
  Severity: refactor

Metrics/BlockLength:
  Severity: refactor

RSpec/ContextWording:
  Severity: refactor

RSpec/ExampleLength:
  Severity: refactor

RSpec/NestedGroups:
  Severity: refactor

RSpec/MessageChain:
  Severity: refactor

Metrics/AbcSize:
  Severity: refactor

Metrics/CyclomaticComplexity:
  Severity: refactor

Metrics/PerceivedComplexity:
  Severity: refactor

Rails/FilePath:
  Severity: refactor

RSpec/ExpectChange:
  Severity: refactor

Style/RedundantFetchBlock:
  Severity: refactor

Rails/IndexWith:
  Severity: refactor
