ACTION_AND_RESOURCES = [
  { name: 'index', resource: 'locations' },
  { name: 'index', resource: 'wedges' },
  { name: 'show', resource: 'wedges' },
  { name: 'create', resource: 'wedges' },
  { name: 'update', resource: 'wedges' },
  { name: 'destroy', resource: 'wedges' },
  { name: 'index', resource: 'visits' },
  { name: 'show', resource: 'visits' },
  { name: 'create', resource: 'visits' },
  { name: 'update', resource: 'visits' },
  { name: 'destroy', resource: 'visits' },
  { name: 'index', resource: 'users' },
  { name: 'show', resource: 'users' },
  { name: 'create', resource: 'users' },
  { name: 'update', resource: 'users' },
  { name: 'destroy', resource: 'users' },
  { name: 'users_confirm_account', resource: 'users' },
  { name: 'change_status', resource: 'users' },
  { name: 'index', resource: 'teams' },
  { name: 'show', resource: 'teams' },
  { name: 'create', resource: 'teams' },
  { name: 'update', resource: 'teams' },
  { name: 'destroy', resource: 'teams' },
  { name: 'index', resource: 'states' },
  { name: 'show', resource: 'states' },
  { name: 'create', resource: 'states' },
  { name: 'update', resource: 'states' },
  { name: 'destroy', resource: 'states' },
  { name: 'index', resource: 'special_places' },
  { name: 'show', resource: 'special_places' },
  { name: 'create', resource: 'special_places' },
  { name: 'update', resource: 'special_places' },
  { name: 'destroy', resource: 'special_places' },
  { name: 'index', resource: 'roles' },
  { name: 'show', resource: 'roles' },
  { name: 'create', resource: 'roles' },
  { name: 'update', resource: 'roles' },
  { name: 'destroy', resource: 'roles' },
  { name: 'index', resource: 'questionnaires' },
  { name: 'show', resource: 'questionnaires' },
  { name: 'create', resource: 'questionnaires' },
  { name: 'current', resource: 'questionnaires' },
  { name: 'list_to_visit', resource: 'houses' },
  { name: 'update', resource: 'questionnaires' },
  { name: 'destroy', resource: 'questionnaires' },
  { name: 'index', resource: 'permissions' },
  { name: 'show', resource: 'permissions' },
  { name: 'create', resource: 'permissions' },
  { name: 'update', resource: 'permissions' },
  { name: 'destroy', resource: 'permissions' },
  { name: 'index', resource: 'organizations' },
  { name: 'show', resource: 'organizations' },
  { name: 'create', resource: 'organizations' },
  { name: 'update', resource: 'organizations' },
  { name: 'destroy', resource: 'organizations' },
  { name: 'index', resource: 'neighborhoods' },
  { name: 'show', resource: 'neighborhoods' },
  { name: 'create', resource: 'neighborhoods' },
  { name: 'update', resource: 'neighborhoods' },
  { name: 'destroy', resource: 'neighborhoods' },
  { name: 'index', resource: 'houses' },
  { name: 'show', resource: 'houses' },
  { name: 'create', resource: 'houses' },
  { name: 'update', resource: 'houses' },
  { name: 'destroy', resource: 'houses' },
  { name: 'index', resource: 'house_blocks' },
  { name: 'show', resource: 'house_blocks' },
  { name: 'create', resource: 'house_blocks' },
  { name: 'update', resource: 'house_blocks' },
  { name: 'destroy', resource: 'house_blocks' },
  { name: 'index', resource: 'get_last_params' },
  { name: 'show', resource: 'get_last_params' },
  { name: 'create', resource: 'get_last_params' },
  { name: 'index', resource: 'countries' },
  { name: 'show', resource: 'countries' },
  { name: 'create', resource: 'countries' },
  { name: 'update', resource: 'countries' },
  { name: 'destroy', resource: 'countries' },
  { name: 'index', resource: 'cities' },
  { name: 'show', resource: 'cities' },
  { name: 'create', resource: 'cities' },
  { name: 'update', resource: 'cities' },
  { name: 'destroy', resource: 'cities' },
  { name: 'find_address', resource: 'get_address' },
  { name: 'change_team', resource: 'users' },
  { name: 'house_status', resource: 'reports' },
  { name: 'delete_account', resource: 'users' },
  { name: 'brigadists_performance', resource: 'reports' },
  { name: 'tariki_houses', resource: 'reports' },
  { name: 'index', resource: 'reports' },
  { name: 'update', resource: 'inspections' },
  { name: 'delete', resource: 'inspections' },
  { name: 'show', resource: 'inspections' },
  { name: 'create', resource: 'inspections' },
  { name: 'index', resource: 'inspections' },
  { name: 'delete', resource: 'visits' },
  { name: 'orphan_houses', resource: 'houses' },
  { name: 'house_blocks', resource: 'create' },
  { name: 'house_blocks', resource: 'update' },
  { name: 'house_blocks', resource: 'wedges' },
  { name: 'accumulated_points', resource: 'points' },
  { name: 'ranking', resource: 'points' },
  { name: 'update_password', resource: 'users' }
].freeze

ROLES_PERMISSIONS = {
  roles: [
    {
      name: 'brigadista',
      permissions: [
        { name: 'create', resource: 'visits' },
        { name: 'index', resource: 'special_places' },
        { name: 'show', resource: 'special_places' },
        { name: 'index', resource: 'questionnaires' },
        { name: 'show', resource: 'questionnaires' },
        { name: 'current', resource: 'questionnaires' },
        { name: 'index', resource: 'houses' },
        { name: 'show', resource: 'houses' },
        { name: 'create', resource: 'houses' },
        { name: 'list_to_visit', resource: 'houses' },
        { name: 'show', resource: 'house_blocks' },
        { name: 'index', resource: 'get_last_params' },
        { name: 'find_address', resource: 'get_address' },
        { name: 'create', resource: 'posts' },
        { name: 'index', resource: 'posts' },
        { name: 'show', resource: 'posts' },
        { name: 'update', resource: 'posts' },
        { name: 'destroy', resource: 'posts' },
        { name: 'like', resource: 'posts' },
        { name: 'create', resource: 'comments' },
        { name: 'index', resource: 'comments' },
        { name: 'show', resource: 'comments' },
        { name: 'update', resource: 'comments' },
        { name: 'destroy', resource: 'comments' },
        { name: 'like', resource: 'comments' },
        { name: 'house_status', resource: 'reports' },
        { name: 'delete_account', resource: 'users' },
        { name: 'brigadists_performance', resource: 'reports' },
        { name: 'tariki_houses', resource: 'reports' },
        { name: 'house_blocks', resource: 'wedges' },
        { name: 'accumulated_points', resource: 'points' },
        { name: 'ranking', resource: 'points' },
        { name: 'update_password', resource: 'users' },
        { name: 'update', resource: 'houses' }
      ]
    },
    {
      name: 'facilitador',
      permissions: [
        { name: 'create', resource: 'wedges' },
        { name: 'index', resource: 'visits' },
        { name: 'show', resource: 'visits' },
        { name: 'create', resource: 'visits' },
        { name: 'index', resource: 'questionnaires' },
        { name: 'show', resource: 'questionnaires' },
        { name: 'current', resource: 'questionnaires' },
        { name: 'index', resource: 'houses' },
        { name: 'show', resource: 'houses' },
        { name: 'create', resource: 'houses' },
        { name: 'list_to_visit', resource: 'houses' },
        { name: 'index', resource: 'house_blocks' },
        { name: 'show', resource: 'house_blocks' },
        { name: 'index', resource: 'get_last_params' },
        { name: 'index', resource: 'teams' },
        { name: 'show', resource: 'teams' },
        { name: 'create', resource: 'teams' },
        { name: 'update', resource: 'teams' },
        { name: 'destroy', resource: 'teams' },
        { name: 'index', resource: 'users' },
        { name: 'show', resource: 'users' },
        { name: 'update', resource: 'users' },
        { name: 'change_status', resource: 'users' },
        { name: 'users_confirm_account', resource: 'users' },
        { name: 'index', resource: 'special_places' },
        { name: 'show', resource: 'special_places' },
        { name: 'find_address', resource: 'get_address' },
        { name: 'index', resource: 'wedges' },
        { name: 'change_team', resource: 'users' },
        { name: 'create', resource: 'posts' },
        { name: 'index', resource: 'posts' },
        { name: 'show', resource: 'posts' },
        { name: 'update', resource: 'posts' },
        { name: 'destroy', resource: 'posts' },
        { name: 'like', resource: 'posts' },
        { name: 'create', resource: 'comments' },
        { name: 'index', resource: 'comments' },
        { name: 'show', resource: 'comments' },
        { name: 'update', resource: 'comments' },
        { name: 'destroy', resource: 'comments' },
        { name: 'like', resource: 'comments' },
        { name: 'house_status', resource: 'reports' },
        { name: 'delete_account', resource: 'users' },
        { name: 'brigadists_performance', resource: 'reports' },
        { name: 'show', resource: 'inspections' },
        { name: 'index', resource: 'inspections' },
        { name: 'house_blocks', resource: 'wedges' },
        { name: 'accumulated_points', resource: 'points' },
        { name: 'ranking', resource: 'points' },
        { name: 'update_password', resource: 'users' },
        { name: 'update', resource: 'houses' }
      ]
    },
    {
      name: 'admin',
      permissions: ACTION_AND_RESOURCES
    }
  ]
}.freeze
