# frozen_string_literal: true

ACTION_AND_RESOURCES = [
  { name: 'index', resource: 'locations' },
  { name: 'index', resource: 'wedges' },
  { name: 'show', resource: 'wedges' },
  { name: 'create', resource: 'wedges' },
  { name: 'update', resource: 'wedges' },
  { name: 'destroy', resource: 'wedges' },
  { name: 'index', resource: 'visits' },
  { name: 'show', resource: 'visits' },
  { name: 'create', resource: 'visits' },
  { name: 'update', resource: 'visits' },
  { name: 'destroy', resource: 'visits' },
  { name: 'index', resource: 'users' },
  { name: 'show', resource: 'users' },
  { name: 'create', resource: 'users' },
  { name: 'update', resource: 'users' },
  { name: 'destroy', resource: 'users' },
  { name: 'users_confirm_account', resource: 'users' },
  { name: 'index', resource: 'teams' },
  { name: 'show', resource: 'teams' },
  { name: 'create', resource: 'teams' },
  { name: 'update', resource: 'teams' },
  { name: 'destroy', resource: 'teams' },
  { name: 'index', resource: 'states' },
  { name: 'show', resource: 'states' },
  { name: 'create', resource: 'states' },
  { name: 'update', resource: 'states' },
  { name: 'destroy', resource: 'states' },
  { name: 'index', resource: 'special_places' },
  { name: 'show', resource: 'special_places' },
  { name: 'create', resource: 'special_places' },
  { name: 'update', resource: 'special_places' },
  { name: 'destroy', resource: 'special_places' },
  { name: 'index', resource: 'roles' },
  { name: 'show', resource: 'roles' },
  { name: 'create', resource: 'roles' },
  { name: 'update', resource: 'roles' },
  { name: 'destroy', resource: 'roles' },
  { name: 'index', resource: 'questionnaires' },
  { name: 'show', resource: 'questionnaires' },
  { name: 'create', resource: 'questionnaires' },
  { name: 'current', resource: 'questionnaires' },
  { name: 'list_to_visit', resource: 'houses' },
  { name: 'update', resource: 'questionnaires' },
  { name: 'destroy', resource: 'questionnaires' },
  { name: 'index', resource: 'permissions' },
  { name: 'show', resource: 'permissions' },
  { name: 'create', resource: 'permissions' },
  { name: 'update', resource: 'permissions' },
  { name: 'destroy', resource: 'permissions' },
  { name: 'index', resource: 'organizations' },
  { name: 'show', resource: 'organizations' },
  { name: 'create', resource: 'organizations' },
  { name: 'update', resource: 'organizations' },
  { name: 'destroy', resource: 'organizations' },
  { name: 'index', resource: 'neighborhoods' },
  { name: 'show', resource: 'neighborhoods' },
  { name: 'create', resource: 'neighborhoods' },
  { name: 'update', resource: 'neighborhoods' },
  { name: 'destroy', resource: 'neighborhoods' },
  { name: 'index', resource: 'houses' },
  { name: 'show', resource: 'houses' },
  { name: 'create', resource: 'houses' },
  { name: 'update', resource: 'houses' },
  { name: 'destroy', resource: 'houses' },
  { name: 'index', resource: 'house_blocks' },
  { name: 'show', resource: 'house_blocks' },
  { name: 'create', resource: 'house_blocks' },
  { name: 'update', resource: 'house_blocks' },
  { name: 'destroy', resource: 'house_blocks' },
  { name: 'index', resource: 'get_last_params' },
  { name: 'show', resource: 'get_last_params' },
  { name: 'create', resource: 'get_last_params' },
  { name: 'index', resource: 'countries' },
  { name: 'show', resource: 'countries' },
  { name: 'create', resource: 'countries' },
  { name: 'update', resource: 'countries' },
  { name: 'destroy', resource: 'countries' },
  { name: 'index', resource: 'cities' },
  { name: 'show', resource: 'cities' },
  { name: 'create', resource: 'cities' },
  { name: 'update', resource: 'cities' },
  { name: 'destroy', resource: 'cities' }
].freeze


ROLES_PERMISSIONS = {
  roles: [
    {
      name: 'brigadista',
      permissions: [
        { name: 'create', resource: 'visits' },
        { name: 'index', resource: 'special_places' },
        { name: 'show', resource: 'special_places' },
        { name: 'index', resource: 'questionnaires' },
        { name: 'show', resource: 'questionnaires' },
        { name: 'current', resource: 'questionnaires' },
        { name: 'index', resource: 'houses' },
        { name: 'show', resource: 'houses' },
        { name: 'create', resource: 'houses' },
        { name: 'list_to_visit', resource: 'houses' },
        { name: 'index', resource: 'house_blocks' },
        { name: 'show', resource: 'house_blocks' },
        { name: 'index', resource: 'get_last_params' }
      ]
  },
    {
      name: 'team_leader',
      permissions: [
        { name: 'create', resource: 'wedges' },
        { name: 'index', resource: 'visits' },
        { name: 'show', resource: 'visits' },
        { name: 'create', resource: 'visits' },
        { name: 'index', resource: 'questionnaires' },
        { name: 'show', resource: 'questionnaires' },
        { name: 'current', resource: 'questionnaires' },
        { name: 'index', resource: 'houses' },
        { name: 'show', resource: 'houses' },
        { name: 'create', resource: 'houses' },
        { name: 'list_to_visit', resource: 'houses' },
        { name: 'index', resource: 'house_blocks' },
        { name: 'show', resource: 'house_blocks' },
        { name: 'index', resource: 'get_last_params' },
        { name: 'index', resource: 'teams' },
        { name: 'show', resource: 'teams' },
        { name: 'create', resource: 'teams' },
        { name: 'update', resource: 'teams' },
        { name: 'destroy', resource: 'teams' },
        { name: 'index', resource: 'users' },
        { name: 'show', resource: 'users' },
        { name: 'update', resource: 'users' },
        { name: 'users_confirm_account', resource: 'users' },
        { name: 'index', resource: 'special_places' },
        { name: 'show', resource: 'special_places' },
      ]
    },
    {
      name: 'admin',
      permissions: [
        { name: 'index', resource: 'locations' },
        { name: 'create', resource: 'houses' },
        { name: 'create', resource: 'wedges' },
        { name: 'index', resource: 'wedges' },
        { name: 'show', resource: 'wedges' },
        { name: 'update', resource: 'wedges' },
        { name: 'destroy', resource: 'wedges' },
        { name: 'index', resource: 'visits' },
        { name: 'update', resource: 'visits' },
        { name: 'destroy', resource: 'visits' },
        { name: 'index', resource: 'users' },
        { name: 'show', resource: 'users' },
        { name: 'update', resource: 'users' },
        { name: 'destroy', resource: 'users' },
        { name: 'users_confirm_account', resource: 'users' },
        { name: 'index', resource: 'teams' },
        { name: 'show', resource: 'teams' },
        { name: 'create', resource: 'teams' },
        { name: 'update', resource: 'teams' },
        { name: 'destroy', resource: 'teams' },
        { name: 'create', resource: 'states' },
        { name: 'index', resource: 'states' },
        { name: 'show', resource: 'states' },
        { name: 'update', resource: 'states' },
        { name: 'destroy', resource: 'states' },
        { name: 'index', resource: 'special_places' },
        { name: 'show', resource: 'special_places' },
        { name: 'create', resource: 'special_places' },
        { name: 'update', resource: 'special_places' },
        { name: 'destroy', resource: 'special_places' },
        { name: 'create', resource: 'roles' },
        { name: 'index', resource: 'roles' },
        { name: 'show', resource: 'roles' },
        { name: 'update', resource: 'roles' },
        { name: 'destroy', resource: 'roles' },
        { name: 'index', resource: 'questionnaires' },
        { name: 'show', resource: 'questionnaires' },
        { name: 'create', resource: 'questionnaires' },
        { name: 'update', resource: 'questionnaires' },
        { name: 'destroy', resource: 'questionnaires' },
        { name: 'create', resource: 'permissions' },
        { name: 'index', resource: 'permissions' },
        { name: 'show', resource: 'permissions' },
        { name: 'update', resource: 'permissions' },
        { name: 'destroy', resource: 'permissions' },
        { name: 'create', resource: 'organizations' },
        { name: 'index', resource: 'organizations' },
        { name: 'show', resource: 'organizations' },
        { name: 'update', resource: 'organizations' },
        { name: 'destroy', resource: 'organizations' },
        { name: 'create', resource: 'neighborhoods' },
        { name: 'index', resource: 'neighborhoods' },
        { name: 'show', resource: 'neighborhoods' },
        { name: 'update', resource: 'neighborhoods' },
        { name: 'destroy', resource: 'neighborhoods' },
        { name: 'index', resource: 'houses' },
        { name: 'show', resource: 'houses' },
        { name: 'update', resource: 'houses' },
        { name: 'destroy', resource: 'houses' },
        { name: 'index', resource: 'house_blocks' },
        { name: 'show', resource: 'house_blocks' },
        { name: 'create', resource: 'house_blocks' },
        { name: 'update', resource: 'house_blocks' },
        { name: 'destroy', resource: 'house_blocks' },
        { name: 'index', resource: 'get_last_params' },
        { name: 'create', resource: 'countries' },
        { name: 'index', resource: 'countries' },
        { name: 'show', resource: 'countries' },
        { name: 'update', resource: 'countries' },
        { name: 'destroy', resource: 'countries' },
        { name: 'create', resource: 'cities' },
        { name: 'index', resource: 'cities' },
        { name: 'show', resource: 'cities' },
        { name: 'update', resource: 'cities' },
        { name: 'destroy', resource: 'cities' },
        { name: 'show', resource: 'visits' },
        { name: 'create', resource: 'visits' },
        { name: 'current', resource: 'questionnaires' },
        { name: 'list_to_visit', resource: 'houses' }
      ]
    }
  ]
}.freeze
