:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
:max_retries: 3
:queues:
    - default
    - mailers
:scheduler:
    :listened_queues_only: true
    :schedule:
        sync_houses_job:
            cron: '30 14 * * 1'
            class: Houses::SyncHouses
            queue: default
            enabled: true
            description: "Sync houses every Sunday at 01:00 AM"
production:
    :concurrency: 20
